#!/bin/sh
#
# Usage: ampere-centos-build.sh <build-tag>
#
#  where  the build-tag format is YYMMDD where YY is last year digit, MM is month, and DD is day
#
# NOTE: build-tag is auto generated by date if not provided.
#
# These need to match with the definition in .spec file
#
echo off
AMP_TOOLCHAIN_VER=9.0.7-le
AMP_COMPILER_PATH=/opt/amp/${AMP_TOOLCHAIN_VER}/usr/bin
CROSS_COMPILER_PATH=/tools/arm/armv8/Theobroma/opt/amp-aarch64/${AMP_TOOLCHAIN_VER}/bin

MACHINE_TYPE=`uname -m`

if [ ${MACHINE_TYPE} = 'aarch64' ]; then
   export -n CROSS_COMPILE
   if [ -d "$AMP_COMPILER_PATH" ]; then
        PATH=${AMP_COMPILER_PATH}:$PATH
        export PATH
   fi
fi
if [ ${MACHINE_TYPE} = 'x86_64' ]; then
   export CROSS_COMPILE=aarch64-apm-linux-gnu-
   if [ -d "$CROSS_COMPILER_PATH" ]; then
        PATH=${CROSS_COMPILER_PATH}:$PATH
        export PATH
   fi
fi

TODAY=`date +%y%m%d`
RELBUILD="${TODAY}"
if [ -n "${1}" ]; then
	RELBUILD=${1}
fi

CENTOSNAMEPREFIX=amp_sw_centos_7.5
CENTOSSPECFILE=SPECS/kernel-emag.spec
CENTOSOPTIMIZESPECFILE=SPECS/kernel-emag-optimized.spec
RPMVERSION=`grep -e "^%define rpmversion" ${CENTOSSPECFILE} | cut -d' ' -f3`
PKGRELEASE=`grep -e "^%define pkgrelease" ${CENTOSSPECFILE} | cut -d' ' -f3`

rpmversion=${RPMVERSION}
pkgrelease=${PKGRELEASE}

# Prepare Linux source in SOURCES/
LINUX_SRC=linux-${rpmversion}-${pkgrelease}
rm -fr ${LINUX_SRC} SOURCES/linux-${rpmversion}-${pkgrelease}.tar.xz
cp -r ../ampere-centos-kernel ${LINUX_SRC}
cd ${LINUX_SRC};make distclean;rm -fr .git;cd -
tar -cJf SOURCES/linux-${rpmversion}-${pkgrelease}.tar.xz ${LINUX_SRC}
rm -fr ${LINUX_SRC} RPMS/aarch64/* SRPMS/*

echo "Building for generic release tag ${RELBUILD}"

#Update build release tag to spec file
#sed -i "s/ buildid \..*/ buildid \.${RELBUILD}+amp/g" ${CENTOSSPECFILE}

rpmbuild --target aarch64 --define "%_topdir `pwd`" --define "buildid .${RELBUILD}+amp" --without debug --without debuginfo --without tools --without perf -ba ${CENTOSSPECFILE}

cd RPMS/aarch64; md5sum *.rpm > ${CENTOSNAMEPREFIX}-${RELBUILD}_md5sum.txt; cd -
cd RPMS/; tar -cJf ../${CENTOSNAMEPREFIX}-${RELBUILD}.tar.xz aarch64;cd -
tar -cJf ${CENTOSNAMEPREFIX}-${RELBUILD}.src.tar.xz SRPMS

rm -rf RPMS/aarch64/* SRPMS/*

echo "Building for optimized release tag ${RELBUILD}"

#Update build release tag to spec file
#sed -i "s/ buildid \..*/ buildid \.${RELBUILD}+amp.ilp32/g" ${CENTOSOPTIMIZESPECFILE}

rpmbuild --target aarch64 --define "%_topdir `pwd`" --define "buildid .${RELBUILD}+amp.ilp32" --without debug --without debuginfo --without tools --without perf -ba ${CENTOSOPTIMIZESPECFILE}

cd RPMS/aarch64; md5sum *.rpm > ${CENTOSNAMEPREFIX}-${RELBUILD}.ilp32_md5sum.txt; cd -
cd RPMS/; tar -cJf ../${CENTOSNAMEPREFIX}-${RELBUILD}.ilp32.tar.xz aarch64;cd -
tar -cJf ${CENTOSNAMEPREFIX}-${RELBUILD}.ilp32-src.tar.xz SRPMS
rm -fr RPMS/aarch64/* SRPMS/*
